Repository cap-ntu/Video-to-Retail-Platform, pull requests merged in 2020-06, with the labels that each got.

#40 [quick fix] :ambulance: Plugin service quick fix
  v2_plugin/example/maskrcnn-service/engine.py
  v2_plugin/protos/infer.proto
  v2_plugin/runner/common/servicer.py
  v2_plugin/runner/main.py
Labels: bug

#42 [feature] Plugin service
  v2_plugin/README.md
  v2_plugin/client/__init__.py
  v2_plugin/client/make_request_util.py
  v2_plugin/client/rpc_client.py
  v2_plugin/example/maskrcnn-service/engine.py
  v2_plugin/example/maskrcnn-service/install.sh
  v2_plugin/example/maskrcnn-service/service.yml
  v2_plugin/test/test_grpc.py
  v2_plugin/test/test_http.py
Labels: enhancement

#48 [Quick fix] :book: Update v2 service plugin docs
  v2_plugin/README.md
Labels: documentation

#51 [Quick fix] Plugin service example
  CONTRIBUTING.md
  README.md
  environment.yml
  server/static/css/keen-dashboards.css
  server/static/css/mystyle.css
  server/static/js/keen-analytics.js
  server/static/js/myVideoPlayer.js
  server/static/js/utils.js
  server/templates/registration/login.html
  v2_plugin/example/hello-world/engine.py
  v2_plugin/example/hello-world/install.sh
  v2_plugin/example/hello-world/predictor.py
  v2_plugin/example/hello-world/service.yml
Labels: bug

#55 [CI] fix Travis CI
  .travis.yml
  README.md
  scripts/build.sh
  tests/test_all.py
Labels: bug, enhancement

#56 [docs] fix url
  README.md
  docs/Showcase.md
Labels: documentation
